[package]
name = "person-protocol"
version = "0.1.0"
edition = "2024"

[dependencies]
eyre = "0.6.12"
log = "0.4.33"
n0-error = "1.0.0"
iroh = { version = "1.0.1", default-features = false }
rkyv = "0.8.17"
serde = { version = "1.0.228", features = ["derive"] }
strum = { version = "0.28.0", features = ["derive"] }
futures = "0.3.32"
async-channel = "2.5.0"
